### ISSUE TITLE
コンソールを動かそうとするときにエラーがでる

### ISSUE THREAD

**Issue by IwaseMio** [shinonome-inc/mobile_Mio_basic_flutter#2]
```dart
import 'dart:math';
import 'dart:io';

// enum:特定の値のみが列挙型で定義された値の中から選択できる
enum Hand { rock, paper, scissors }

void playRockPaperScissors(Hand myHand) {
  final random = Random();
  final computerHandIndex = random.nextInt(3);
  final computerHand = Hand.values[computerHandIndex];

  print('Player choose: $myHand');
  print('Computer choose: $computerHand');

  if (myHand == computerHand) {
    print('引き分けや、もう一度勝負しよ');
  } else if ((myHand == Hand.rock && computerHand == Hand.scissors) ||
      (myHand == Hand.paper && computerHand == Hand.rock) ||
      (myHand == Hand.scissors && computerHand == Hand.paper)) {
    print('ワイの負けや。強いな');
  } else {
    print('YOU LOSE 俺の勝ち。何で負けたか、明日まで考えといてください');
  }
}

void main() {
  // プレイヤーの手を入力
  print('じゃんけんしようや (0 for Rock, 1 for Paper, 2 for Scissors):');
  final input = int.parse(stdin.readLineSync() ?? '');

  // 入力を Hand 列挙体に変換して関数に渡す
  if (input == 0 || input == 1 || input == 2) {
    final myHand = Hand.values[input];
    playRockPaperScissors(myHand);
  } else {
    print('Invalid choice. Please choose between 0, 1, or 2.');
  }
}
```

**Comment by IwaseMio** [comment]
Unknown evaluation response type: null
#0      DartDebugAdapter.evaluateRequest (package:dds/src/dap/adapters/dart.dart:1076:7)
#1      BaseDebugAdapter.handle (package:dds/src/dap/base_debug_adapter.dart:141:20)
#2      BaseDebugAdapter.handleIncomingRequest (package:dds/src/dap/base_debug_adapter.dart:447:7)
#3      BaseDebugAdapter._handleIncomingMessage (package:dds/src/dap/base_debug_adapter.dart:295:7)
#4      ByteStreamServerChannel._readMessage (package:dds/src/dap/protocol_stream.dart:82:18)
#5      ByteStreamServerChannel.listen.<anonymous closure> (package:dds/src/dap/protocol_stream.dart:53:24)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#9      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

**Comment by KobayashiYoh** [comment]
僕の環境だと問題なく実行できました🤔
```
じゃんけんしようや (0 for Rock, 1 for Paper, 2 for Scissors):
0
Player choose: Hand.rock
Computer choose: Hand.scissors
ワイの負けや。強いな

Process finished with exit code 0
```
